- name: Configuring the {{COMPONENT}} Repository
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing the {{COMPONENT}} Package
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Enabling the {{COMPONENT}} Visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restarting the {{COMPONENT}} Service
  ansible.builtin.systemd: 
    name: mongod 
    state: restarted
    enabled: true
    daemon_reload: true

- name: Download and Extracting {{COMPONENT}} Schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: true

- name: Injecting User Component Schema
  community.mongodb.mongodb_shell:
# Our databse version 4 is not going to mandate username and password, so wer are not providing it.
    # login_user: user
    # login_password: secret
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop: 
    - users
    - catalogue 