- name: Configuring the {{COMPONENT}} Repository
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
    
- name: Installing the {{COMPONENT}} Package
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Enabling the {{COMPONENT}} Visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restarting the {{COMPONENT}} Service
  ansible.builtin.systemd: 
    name: mongod 
    state: restarted
    enabled: true
    daemon_reload: true