# Usage of shell module is strictly restricted  unless you don't have a relevent module in ANSIBLE Collections

# Shell Module helps us to run the exact shell commands on playbook

- name: Demo on usage of shell module
  hosts: all
  task: 
    - name: Running the uptime shell command 
      ansible.builtin.shell: uptime