- name: Demo on Conditions 
  hosts: all
  vars: 
    action: false
  tasks:
    - name: Run this task only when the OS Distribution is CentOS
      ansible.builtin.debug:
        msg: OS Distribution is {{ansible_distribution}}
      when: ansible_distribution == "CentOS"
    
    - name: Run this task only when the OS Distribution is Ubuntu
      ansible.builtin.debug:
        msg: OS Distribution is {{ansible_distribution}}
      when: ansible_distribution == "Ubuntu" #Here this task will be ignored since we are using centos ami

    - name: Run this action 
      ansible.builtin.debug:
        msg: Action is true  
      when: action   #Here this task will be ignored since action value we declared as false

    - name: Run this action when action is declared/defined
      ansible.builtin.debug:
        msg: Action is defined
      when: action is defined # Here 'is' and 'defined' is keyword this task will be executed since we have declared the action variable

    - name: Run this action when action is not declared/defined
      ansible.builtin.debug:
        msg: Action is defined
      when: action is undefined # Here 'is' and 'undefined' is keyword this task will not be executed since we have declared the action variable  