- name: Installing ERLANG
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash


- name: Configuring the {{COMPONENT}} Repository
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash
 
- name: Installing the {{COMPONENT}} Package
  ansible.builtin.package:
    name: rabbitmq-server 
    state: present

- name: Starting {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Creating {{APPUSER}} user 
  community.rabbitmq.rabbitmq_user:
    user: "{{APPUSER}}" 
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present