- name: Copying the Logstash Configuration File
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restarting logstash Service
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Wait for Logstash to Start
  ansible.builtin.wait_for:
    port: 5044
    delay: 30
    timeout: 60
# Any Change made to the logstash.conf file would need a restart to function properly
