- name: Configuring {{COMPONENT}} Repository
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Installing the {{COMPONENT}} Package
  ansible.builtin.package:
    name: 
      - mysql-community-server
      - python3-PyMySQL
      - MySQL-python
    state: present

- name: Restarting the {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true

- name: Extracting the mysql log file
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: psw_log 

# If any of the task in block fails, The task in the rescue will be executed. This is exception handling in the ansible.

- name: Verifying the password 
  block:
    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
        login_user: root 
        login_password: "{{MYSQL_PSWD}}"
        filter: version
  rescue: 
    - name: Extracting the password from logfile
      ansible.builtin.set_fact:
        DEFAULT_PASSWORD: "{{psw_log['content'] | b64decode | regex_findall('.*temporary password.*') | join('') | split(' ') | last}}"

    - name: Changing Default Root Password
      ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASSWORD}}"
