- name: Installing Maven for {{COMPONENT}}
  ansible.builtin.shell: curl https://gitlab.com/thecloudcareers/opensource/-/raw/master/lab-tools/maven-java11/install.sh | bash # || true
  ignore_errors: true

- name: Creating User Account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

# Uncomment below code if you want to download the code from github
# - name: Configuring the {{COMPONENT}}
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download_&_extract

- name: Downloading the Artifacts from Nexus
  ansible.builtin.include_role:
    name: common
    tasks_from: download_from_nexus

# Uncomment below code if you want to generate artifacts for code which is downloaded from github
# - name: Installing the {{COMPONENT}} Artifacts
#   ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
#   args:
#     chdir: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring and Starting the {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring the RSYSLOG
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog

- name: Configuring the Beats
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat
  
- name: Installing Node Exporter 
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node_exporter

- name: Set Hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: set_hostname
