- name: Installing the Python
  ansible.builtin.package:
    name:
      - python36
      - gcc
      - python3-devel
    state: present

- name: Creating User Account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

# Uncomment below code if you want to download the code from github
# - name: Downloading Artifacts
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download_&_extract

- name: Downloading the Artifacts from Nexus
  ansible.builtin.include_role:
    name: common
    tasks_from: download_from_nexus

- name: Updating the UID in {{COMPONENT}}.ini File
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: "^uid"
    line: uid = {{USERINFO.uid}}

- name: Updating the GID in {{COMPONENT}}.ini File
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: "^gid"
    line: gid = {{USERINFO.group}} #.group because in ansible its fethched as group instead of gid

- name: Update gcc
  community.general.alternatives:
    name: gcc
    path: /usr/bin/gcc
    link: /usr/bin/gcc
  become: true

- name: Installing app dependencies
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
    executable: pip3.6

- name: Configuring and Starting Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring the RSYSLOG
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog

- name: Configuring the Beats
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat

- name: Installing Node Exporter 
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: node_exporter    

- name: Set Hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: set_hostname
